[2018-06-27 22:34:01,582] {bTrial.py <module>:18} DEBUG - Succesfully loaded Adafruit_DHT
[2018-06-27 22:34:01,789] {bTrial.py loadConfigFile:167} DEBUG - loadConfigFile
[2018-06-27 22:34:01,888] {bTrial.py lightsThread:605} DEBUG - lightsThread start
[2018-06-27 22:34:01,888] {bTrial.py initGPIO_:293} DEBUG - Initialized DHT temperature sensor
[2018-06-27 22:34:01,891] {bTrial.py tempThread:633} INFO - tempThread() start
[2018-06-27 22:34:02,423] {treadmill.py run:78} DEBUG - mySerialThread starting
[2018-06-27 22:34:02,519] {treadmill_app.py <module>:241} DEBUG - Running flask server with debug = False
[2018-06-27 22:34:02,532] {treadmill_app.py <module>:244} DEBUG - Flask server is running at: http://192.168.1.4:5010
[2018-06-27 22:34:03,740] {treadmill_app.py myAfterRequest:60} DEBUG - after /
[2018-06-27 22:34:07,070] {treadmill_app.py myAfterRequest:60} DEBUG - after /templates/partials/config_table.html
[2018-06-27 22:34:07,083] {treadmill_app.py myAfterRequest:60} DEBUG - after /templates/partials/motor_table.html
[2018-06-27 22:34:10,630] {bCamera.py arm:249} DEBUG - arm onoff:True okGo:True
[2018-06-27 22:34:10,667] {treadmill_app.py myAfterRequest:60} DEBUG - after /api/action/startArm
[2018-06-27 22:34:10,860] {bCamera.py initCamera:79} ERROR - picamera PiCameraMMALError: Failed to enable connection: Out of resources
